site_name: Y-Arena
site_description: Janelia Turner Lab Y-Arena Odor Rig
site_author: Peter Polidoro

copyright: 'Copyright &copy; 2020 Peter Polidoro'

theme:
  name: 'material'
  language: en
  logo: 'img/y_logo.png'
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: Deep Purple
  font:
    text: Ubuntu
    code: Roboto Mono

repo_name: 'y-arena'
repo_url: 'https://github.com/janelia-experimental-technology/y-arena.git'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: true

nav:
  - Home: index.md
  - Usage:
    - C++: usage/cpp.md
    - Python: usage/python.md
    - Matlab: usage/matlab.md
    - Docker Command Line: usage/cli.md
    - Arena Odors Message: usage/arena_odors_message.md
    - Odors Vector: usage/odors_vector.md
    - SSH: usage/ssh.md
    - Web Console: usage/web_console.md
  - System Architecture:
    - Arena: sa/arena.md
    - Module: sa/module.md
    - Rig: sa/rig.md
  - Hardware:
    - y_arena_odor_controller: hardware/y_arena_odor_controller.md
  - Firmware:
    - YArenaOdorController: firmware/y_arena_odor_controller.md
  - Software:
    - y_arena_odor_controller_ros: software/y_arena_odor_controller_ros.md
  - Setup:
    - ycontroller: setup/ycontroller.md
    - Windows Host: setup/windows_host.md
