site_name: Y-Arena
site_description: Janelia Turner Lab Y-Arena Odor Rig
site_author: Peter Polidoro

copyright: 'Copyright &copy; 2020 Peter Polidoro'

theme:
  name: 'material'
  language: en
  logo: 'y_logo.png'
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: Deep Purple
  font:
    text: Ubuntu
    code: Roboto Mono

repo_name: 'y-arena'
repo_url: 'https://github.com/janelia-experimental-technology/y-arena.git'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: true

nav:
    - Home: index.md
    - Usage:
       - Matlab: usage/matlab.md
       - Linux Command Line: usage/cli.md
       - Arena Odors Message: usage/arena_odors_message.md
       - Odors Vector: usage/odors_vector.md
    - Images:
       - Arena: images/arena.md
       - Module Side: images/module_side.md
       - Module Top: images/module_top.md
       - Module Top Labeled: images/module_top_labeled.md
    - Hardware:
       - y_arena_odor_controller: hardware/y_arena_odor_controller/y_arena_odor_controller.md
    - Firmware:
       - y_arena_odor_controller: hardware/y_arena_odor_controller/y_arena_odor_controller.md
